### ISSUE TITLE
Basic Authorization failure

### ISSUE THREAD

**Issue by fanwu72** [mobz/elasticsearch-head#327] opened 2017-04-07 10:41 UTC
Hi there,

I build head from latest code today. It works with ES 5.3 very well without authorization. 
However when I enabled the authorization, it always failed with 401 error.

I debugged the javascript from chrome and I found some facts.
1. The code does run into the $.ajaxSetup segment. The auth_user and auth_password are correct and even the encrypted credential is correct.
2. **No Authorization field is found in the HTTP header.**
3. Again, it works well without authorization.

Below is the request header copied from chrome debugger. I replaced the real URIs with fake ones.

> Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:authorization
Access-Control-Request-Method:GET
Connection:keep-alive
Host:some_host_2:9200
Origin:http://some_host_1:9100
Referer:http://some_host_1:9100/?base_uri=http://some_host_2:9200&auth_user=admin&auth_password=admin789
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

I am not skilled at javascript nor ajax and this is all I can do. Please kindly help to resolve this issue. 
Thanks in advance.

Best regards,
Ryan

**Comment by philipskokoh** [comment] 2017-04-07 10:52
You need to configure `http.cors.allow-headers: Authorization` in Elasticsearch conf.
https://github.com/mobz/elasticsearch-head#basic-authentication

**Comment by fanwu72** [comment] 2017-04-07 11:01
@philipskokoh Thanks for your quick reply.
I did configure the item you mentioned. Actually the I don't connect to ES directly. I connect to Nginx as a reverse proxy and the authorization is setup in Nginx.
I think the issue is that **No Authorization field is found in the HTTP header** when I pass in the correct url parameters. 

Please kindly share your opinion. 

Best regards,
Ryan

**Comment by mobz** [comment] 2017-04-07 20:33
Chrome debugger will not show the Authorization header even if it is there. You can check for the header using wireshark or similar. I would check that then reverse proxy is passing the auth through.

'm closing the issue since I don't think this is a bug in 'head, but feel free to keep discussing

**Closed by mobz** 2017-04-07 20:33 UTC

**Comment by fanwu72** [comment] 2017-04-07 23:22
@mobz
I can see the authourization header  from chrome debugger when I connect to the proxy directly（not from head）

I checked the HTTP header from client side（chrome debugger）and server side（tcpdump）and I don't see the difference.

Best regards,
Ryan

**Comment by fanwu72** [comment] 2017-04-09 14:59
@mobz I am afraid that nobody saw this issue since you closed it. I understand that it might not be a bug, but it is an issue for me. Is there any other place for discussing?

**Comment by mobz** [comment] 2017-04-10 01:47
@fanwu72 I spent some time on the weekend revisiting the auth area of the app on the back of your bug. I did notice some inconsistencies which I need to look at further. I do know that this feature works (or has in the past worked) for many people who are _not_ using nginx to do auth.
Have you tried using a different browser?

**Comment by fanwu72** [comment] 2017-04-10 11:47
@mobz Many thanks to your effort.
I reinstall nginx and head to the same server. The situation with chrome is the same as before. While trying IE11, es-head is able to access ES(via nginx) WITHOUT authorization. However, accessing to ES(via) nginx from IE directly(not via es-head)  still requires username and password. It is really weird.

I will make more tests and research tomorrow.

Best regards,
Ryan

**Comment by fanwu72** [comment] 2017-04-11 04:54
@mobz 
According to my latest testing, it works in IE 11 while fails to retrieve data in Chrome 57.0.2987.133 (64-bit) or Safari when authorization is required.

**Comment by foonix** [comment] 2017-04-17 09:28
I'm also having this issue, linux Firefox and Chromium.  Connecting to `https://elasticsearch.example.com` prompts for basic auth and then both browsers show the full `Authorization: DEADBEEF` headers in their respective debuggers.

Connecting to `https://es-head.example.com?base_uri=https://elasticsearch.example.com&auth_user=myuser&auth_password=mypassword`, neither browser shows an `Authorization` header in the requests to elasticsearch.  Both receive 401 with `WWW-Authenticate:Basic realm="Elasticsearch web access"` header.

All sites in question are using signed certs.  Everything worked before I added basic auth on the nginx vhosts.

**Comment by Nayar** [comment] 2017-04-20 07:00
Having same issue here. Using `tcpdump`, I can't find the `authorisation` field in the request packet. Same issue with Firefox and Chrome

```
06:55:53.171515 IP x.x.x.x.41384 > 100.64.111.81.9200: Flags [P.], seq 1:580, ack 1, win 229, options [nop,nop,TS val 8006750 ecr 317597687], length 579
E..w.8@.<..G.).Fd@oQ..#..X...NQu...........
.z,^..'.OPTIONS /_all HTTP/1.1
Host: elastics-vigilance.stellatelecom.com:9200
Connection: keep-alive
Access-Control-Request-Method: GET
Origin: http://100.64.111.41:9100
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/57.0.2987.98 Chrome/57.0.2987.98 Safari/537.36
Access-Control-Request-Headers: authorization
Accept: */*
Referer: http://100.64.111.41:9100/?base_uri=http://example.com:9200&auth_user=elastic&auth_password=pak
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8


06:55:53.171654 IP 100.64.111.81.9200 > x.x.x.x.41384: Flags [F.], seq 1:258, ack 580, win 236, options [nop,nop,TS val 317597743 ecr 8006750], length 257
E..5yZ@.@./hd@oQ.).F#....NQu.X.T.....(.....
..(/.z,^HTTP/1.0 401 Unauthorized
Cache-Control: no-cache
Connection: close
Content-Type: text/html
WWW-Authenticate: Basic realm="Elasticsearch"

<html><body><h1>401 Unauthorized</h1>
You need a valid user and password to access this content.
</body></html>
```

**Comment by mobz** [comment] 2017-04-20 09:27
Very strange, I wonder if this is some change in behaviour by chrome, it used to work.

**Comment by Nayar** [comment] 2017-04-27 14:20
Lots of people are having this issue. Think it's a 'bug' right?

**Comment by wimvanleuven** [comment] 2017-05-11 10:51
same issue here on ES behind apache2 proxy

**Comment by wimvanleuven** [comment] 2017-05-11 11:59
I tried Safari as well but same result.

**Comment by C-Duv** [comment] 2018-04-19 13:02
Same issue here using Elasticsearch v6.2.4 behind a Nginx v1.10.3 reverse-proxy and elasticsearch-head version bee08506a964c1b:
Tried both Firefox and Chromium: When accessing the GUI with
http://localhost:9100/?base_uri=https://foo.example.com/es/&auth_user=user&auth_password=secret
my Nginx logs shows unauthenticated requests.

But `curl -D - https://user:secret@foo.example.com/es/` returns 200 HTTP response (and Nginx logs shows the request is from *user*).

Nginx reverse proxy is configured as follows:

```Nginx
upstream elasticsearch {
    server 127.0.0.1:9200;
    keepalive 15;
}

server {
    # ...

    location ~ /es/(?<es_uri>.*) {
         auth_pam              "Forbidden";
         auth_pam_service_name "foobar"; # See file in /etc/pam.d/
 
         # Persistent HTTP Connections
         proxy_set_header Connection "Keep-Alive";
         proxy_set_header Proxy-Connection "Keep-Alive";
 
         # https://sematext.com/blog/elasticsearch-security-authentication-encryption-backup/
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $http_host;
         proxy_set_header X-NginX-Proxy true;
 
         proxy_pass http://elasticsearch/$es_uri;
         proxy_redirect off;
 
         add_header Access-Control-Allow-Origin "*";
         add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS";
         add_header Access-Control-Allow-Headers "Content-Type,Accept,Authorization, x-requested-with";
         add_header Access-Control-Allow-Credentials "true";
         add_header Content-Length 0;
         add_header Content-Type application/json;
     }
     location = /es {
         return 302 /es/;
     }
}
```
(I originally had the `add_header Access-Control-Allow-Origin "*";` only sent for `OPTIONS` method but it created *missing Access-Control-Allow-Origin* error in the browser

I know this is not Nginx bug-tracker but I doubt the issue is Nginx side: it really looks like elasticsearch-head fails to send Basic Auth HTTP headers...

**Comment by kopaygorodsky** [comment] 2018-06-01 00:21
I can confirm that `elasticsearch.username`, `elasticsearch.password` configs don't work. Even custom headers won't help, I don't see any Authorization headers in the request. 
Only `WWW-Authenticate: Basic realm="Insert your Elasticsearch credentials. If you have problems visit: https://docs.bitnami.com/?page=apps&name=elasticsearch"` is present, but have no idea how to force it use credentials. 
Kibana 6.2.4
Elastic: 6.2.4
